import { ProductLang } from './product-lang'
import { CategoryProduct } from './category-product';
import { ProductEvent } from './product-event';
import { ProductItem } from './product-item';
import { ModelProduct } from './model-product';
import { ProductCrossCategory } from './product-cross-category';

export class Product {
    public id_product?: number;
    public id_supplier?: number;
    public id_manufacturer?: number;
    public id_category_default?: number;
    public id_shop_default?: number;
    public id_tax_rules_group?: number;
    public on_sale?: number;
    public online_only?: number;
    public ean13?: string;
    public isbn?: string;
    public upc?: string;
    public ecotax?: number;
    public quantity?: number;
    public minimal_quantity?: number;
    public price?: number;
    public wholesale_price?: number;
    public unity?: string;
    public unit_price_ratio?: number;
    public additional_shipping_cost?: number;
    public reference?: string;
    public supplier_reference?: string;
    public location?: string;
    public width?: number;
    public height?: number;
    public depth?: number;
    public weight?: number;
    public out_of_stock?: number;
    public quantity_discount?: number;
    public customizable?: number;
    public uploadable_files? :number;
    public text_fields?: number;
    public active?:number;
    public redirect_type? :string;
    public id_type_redirected? :number;
    public available_for_order? :number;
    public available_date? :Date;
    public show_condition? :number;
    public condition?:string;
    public show_price? :number;
    public indexed? :number;
    public visibility?:string[];
    public cache_is_pack?:number;
    public cache_has_attachments?:number;
    public is_virtual?:number;
    public cache_default_attribute? :number;
    public date_add? :Date;
    public date_upd? :Date;
    public advanced_stock_management?:number;
    public pack_stock_type? :number;
    public state? :number;
    public ProductLang?:ProductLang;
    public CategoryProduct?:CategoryProduct[];
    public ProductEvent?:ProductEvent;
    public ProductItem?:ProductItem[];
    public ModelProduct?:ModelProduct[];
    public ProductCrossCategory?:ProductCrossCategory[];
    public row_state: string;
    constructor(){
        this.id_product = 0;
        this.id_supplier = 0;
        this.id_manufacturer = 0;
        this.quantity = 0;
        this.reference = "";
        this.condition = "";
        this.row_state = "create";
    }
}
