import { ProductLang } from './product-lang'
import { CategoryProduct } from './category-product';
import { ProductEvent } from './product-event';
import { ProductItem } from './product-item';
import { ProductItemCaracteristica } from './product-item-caracteristica';
import { ProductItemLang } from './product-item-lang';

export interface Product {
     id_product?:number,
     id_supplier? :number,
     id_manufacturer? :number,
     id_category_default?:number,
     id_shop_default? :number,
     id_tax_rules_group? :number,
     on_sale? :number,
     online_only? :number,
     ean13? :string,
     isbn? :string,
     upc? :string,
     ecotax?:number,
     quantity? :number,
     minimal_quantity? :number,
     price?:number,
     wholesale_price? :number,
     unity?:string,
     unit_price_ratio? :number,
     additional_shipping_cost? :number,
     reference? :string,
     supplier_reference? :string,
     location? :string,
     width? :number,
     height? :number,
     depth? :number,
     weight? :number,
     out_of_stock? :number,
     quantity_discount?:number,
     customizable?:number,
     uploadable_files? :number,
     text_fields?:number,
     active?:number,
     redirect_type? :string,
     id_type_redirected? :number,
     available_for_order? :number,
     available_date? :Date,
     show_condition? :number,
     condition?:string,
     show_price? :number,
     indexed? :number,
     visibility?:string[],
     cache_is_pack?:number,
     cache_has_attachments?:number,
     is_virtual?:number,
     cache_default_attribute? :number,
     date_add? :Date,
     date_upd? :Date,
     advanced_stock_management?:number,
     pack_stock_type? :number,
     state? :number,
     ProductLang?:ProductLang,
     CategoryProduct?:CategoryProduct[],
     ProductEvent?:ProductEvent,
     ProductItem?:ProductItem[],
     ProductItemCaracteristica?:ProductItemCaracteristica[],
     ProductItemLang?:ProductItemLang[]
}
